@startuml agency read of owner product


actor Agency
control Server
database product

opt agency read product
  Agency -> Server: DELETE /products/:id
  activate Server
  Server -> Server: check token
  alt <font color="Red">token invalid</font>
    Agency <-- Server: 401, Invalid Token
  else <font color="Green">token valid</font>
    Server -> product: Delete product
    activate product
    Server <-- product: Deleted product
    Agency <-- Server: 204, Deleted product
  end
end


@enduml