@startuml login

actor Customer
control Server
database customers

opt Customer login
  Customer -> Server: Login request
  activate Server
    Server -> customers: Find customer
    activate customers
    alt <font color="Red">customer not found</font>
      customers --> Server: Not found
      Server --> Customer: 404, Customer not found
    else <font color="Green">customer found</font>
      Server -> customers: Login
      customers --> Server: Found customer
      Server --> Server: CreateJWT
      Server --> Customer: 200, Success
      Customer --> Customer: setJWTToLocalStorage
    end
end

@enduml