@startuml create agency admin sequence

actor Admin 
control server
database agency

opt CREATE: Admin create agency
  Admin -> server: POST /agencies/createAgency 
  activate server
  server -> server: check token
  alt <font color=red>token invalid</font>
    server --> Admin: 401, unauthorized error
  else <font color=green>token valid</font>
    server -> server: check isAdmin
    alt <font color=red>is not admin</font>
      server --> Admin: 403, forbidden error
    else <font color=green>is admin</font>
      server -> agency: find agency with email
      activate agency
      alt <font color=red>have error</font>
        agency --> server: error
        server --> Admin: 500, internal error
      else <font color=red>have agency data</font>
        agency --> server: agency data
        server --> Admin: 409, existed agency
      else <font color=green>have no agency data</font>
          server -> agency: create new agency
          alt <font color=red>have error</font>
            agency --> server: error
            server --> Admin: 500, internal error
          else <font color=green>success</font>
            agency --> server: success
            server --> Admin: 200, success
          end
      end
    end
    deactivate agency
    deactivate server
  end
end

@enduml