@startuml agency read of owner product


actor Agency
control Server
database product

opt agency read product
  Agency -> Server: GET /products
  activate Server
  Server -> Server: check token
  alt <font color="Red">token invalid</font>
    Agency <-- Server: 401, Invalid Token
  else <font color="Green">token valid</font>
    Server -> product: Find all products
    activate product
    Server <-- product: productList
    Agency <-- Server: 200, productList
  end
end


@enduml