@startuml customer read agency information

actor Customer
control Server
database product
database agency

opt agency read agency
  Customer -> Server: GET /product/:id/agencies
  activate Server
  Server -> Server: check token
  alt <font color="Red">token invalid</font>
    Customer <-- Server: 401, Invalid Token
  else <font color="Green">token valid</font>
    Server -> product: Find product
    activate product
    alt <font color="Red">product not found</font>
      Server <-- product: product not found
      Customer <-- Server: 404, product not found
    else <font color="Green">product found</font>
    Server <-- product: Found product
    Server -> agency: Find agency with agencyId
      activate agency
      alt <font color="Red">agency not found</font>
        Server <-- agency: agency not found
        Customer <-- Server: 404, agency not found
      else <font color="Green">agency found</font>
        Server <-- agency: Found agency
        Customer <-- Server: 200, Agency information
      end
    end
  end
end

@enduml